### PR TITLE
fix(schema) do not execute code on validation

### LINKED ISSUE #23: When adding a pre/post-function plugin, the function gets executed
I've also opened an [issue](https://github.com/Kong/kong/issues/5010) in Kong's repository, but I'm opening one here as well because I think it might be related to a recent issue that was done here.

So, as you can see in the issue I've opened in Kong, when trying to add a pre/post-function plugin in Kong 1.3, the function I want to add gets executed, which means that if I have something like this in my function:
```lua
if not custom_auth then
  return kong.response.exit(419, "This message is coming from the lua function itself!!!")
end
```
then the POST request to add the plugin gets a 419 status code with this custom message, and I'm unable to add the plugin.
This doesnt happen with Kong 1.0.3 & Kong 1.2

After digging up a bit, I think what's happening is that when Kong is validating the all the plugin's fields and get to the "config" field, it uses the custom_validator which contains the following [code](https://github.com/Kong/kong-plugin-serverless-functions/blob/2636b47cf59e9178335b7a697a40917d377c9d31/kong/plugins/pre-function/_schema.lua#L8):
```lua
local function validate_function(fun)
    local func1, err = loadstring(fun)
    if err then
      return false, "Error parsing " .. plugin_name .. ": " .. err
    end

    local success, func2 = pcall(func1)
```

Now, isn't this code actually executing the function i'm trying to add...?

Thanks! :smile:

### PR DESCRIPTION
**Pull request by hishamhm**
Also, pcall every execution of arbitrary user code. Includes a regression test for Kong/kong#5110

An errors in the return type of the chunk will result in a runtime error like any other, which will be logged and returned as 500 to the client, as usual.

Fixes Kong/kong#5110.
Fixes #23 

edit: added the fix for #23

### CODE REVIEW

File: spec/03-dbless_spec.lua [hunk 1]
```diff
@@ -0,0 +1,57 @@
+local helpers = require "spec.helpers"
```
Comment (Tieske) [inline spec/03-dbless_spec.lua]: This file is not needed, it makes it look like DB less is different from others, which it isn't...

The same test should run on DB-based config.

Comment (kikito) [reply spec/03-dbless_spec.lua]: The `/config` endpoint used on the test is [set to explicitly fail in db-mode](https://github.com/Kong/kong/blob/master/kong/api/routes/config.lua#L24-L29). So an integration test which uses this endpoint needs to be db-less-exclusive.

That said, there *might* be a way to make the test run in db and db-lessm, by using the blueprints abstraction to create the entities (this abstraction will either call `kong.db` or write to a temp file in order to create the entities appropiatedly).

I guess it depends on how one interprets  https://github.com/kong/kong/issues/5110.
* If you "follow the issue to the letter", then we should use the `/config` endpoint, because that's what was done in the issue.
* If you "open your mind a little bit" you can make it work with db-mode as well, but then you are not exactly reproducing the issue any more (you are likely reproducing a *similar* issue which likely stems from the same root problem).

I honestly don't know what is the best approach here.

Comment (Tieske) [reply spec/03-dbless_spec.lua]: you can use the same test (using the exit 418 in the code), but in the 01-access_spec file, as a regular plugin config and not a db-less one.

Comment (hishamhm) [reply spec/03-dbless_spec.lua]: I'm +1 for keeping this as is as a documented regression test for a reported bug.
